### ISSUE TITLE
[0.0.2] When a user changes it's nick capitalization, it dupes on lobby list

### ISSUE THREAD

**Issue by starg09** [Zamiell/isaac-racing-client#1]
[Screenshot of the issue](http://i.imgur.com/yvNSSnk.png)

~~Removes itself after clicking on the old one.~~ **EDIT:** Ok maybe it doesn't. I think "jackie" was the old nick, which remained after clicking both names, and "JACKIE" disappeared because they logged out. Closing and opening removed the other jackie, the one on lowercase.

**EDIT 2:** Yup, JACKIE just logged in. The old capitalization of the nick remains on the online list until user restarts the app.

**Comment by Zamiell** [comment]
Fixed.
