### ISSUE TITLE
Client should remember previous race title

### ISSUE THREAD

**Issue by Hyphen-ated** [Zamiell/isaac-racing-client#13]
When you start a race with a custom ruleset, the title field is currently the only reasonable place to define what the ruleset actually is. (e.g. "unmodded blck cndl")

When doing a series of such races, you have to type or paste that text every time you start a new one. it seems better if the client would remember if you provided a nonrandom title on the last race you started, and if so, default to giving your new race the same name as the previous one. (much like how my hanabi extension remembers your settings for "variant" and "allow spectators")

**Comment by Zamiell** [comment]
Client now remembers it.
