### ISSUE TITLE
Problems with starting the program.

### ISSUE THREAD

**Issue by ItsMrDangeR** [Zamiell/isaac-racing-client#14]
Hello, Zamiell. I have some problems with starting the program. In short, the program needs a 64 bit system, but I have only 32 bit. I can't upgrade my windows to 64 bit system, so, can I ask you to do the 32 bit version of program, please?

**Comment by Zamiell** [comment]
If you run it from source, it should work on a 32-bit Windows.

**Comment by Zamiell** [comment]
32-bit installers are now included in the main installation exe file.
