### ISSUE TITLE
Mod does not work anymore

### ISSUE THREAD

**Issue by PierreEpron** [Zamiell/isaac-racing-client#16]
Hello,

I start isaac with r+ mod like always (work fine before) and nothing work.
- character hasn't d6
- r7+ and other just start isaac normal game
- only start screen and save screen are good

I had unsucribe sucribe, delete manually mods files, reinstall game ....
I have correct 10001% save and a correct options.ini (i think)
No other mod

sorry for my bad english,

have a nice day ;)

**Comment by Zamiell** [comment]
does the log.txt say anything interesting

**Comment by PierreEpron** [comment]
hmm i think yes,
i let you show
https://pastebin.com/1uy3Fbff

**Comment by Zamiell** [comment]
In that log, if you search for "error", you can find:
```
[INFO] - Running Lua Script: C:\Users\Gran Piero/Documents/My Games/Binding of Isaac Afterbirth+ Mods/racing+_857628390/main.lua
[INFO] - ERR: ...ing of Isaac Afterbirth+ Mods/racing+_857628390/main.lua:30: module 'src/rpglobals' not found:
    no file 'resources/scripts/src/rpglobals.lua'
    no file 'C:\Users\Gran Piero/Documents/My Games/Binding of Isaac Afterbirth+ Mods/racing+_857628390/src/rpglobals.lua'
[INFO] - There was an error running the lua file: C:\Users\Gran Piero/Documents/My Games/Binding of Isaac Afterbirth+ Mods/racing+_857628390/main.lua
```
Does this file exist? If not, then its not downloading properly. Redownload it from Steam until that file exists.

**Comment by PierreEpron** [comment]
BInding of Isaac Afterbirth+ Mods/src don't want to copy itself ...
I just take it from depot
It's work now,
Thank you very much
