### ISSUE TITLE
Steam connection fails on Arch Linux (Steam using system libraries)

### ISSUE THREAD

**Issue by ghost** [Zamiell/isaac-racing-client#17]
Hey,

The client is stuck on the load screen and does nothing, when I click on "Steam" in the electron app window. Hotkeys are still working, so it's not frozen.
Installation worked flawlessly without any errors.
Steam is running in the background, when I quit Steam and click on "Steam" in the electron app I get:

> Error
> Steam initialization failed. It appears that Steam is not running. (If it is running, please restart your computer and try again.)

Log on the cli:
>Wed Nov 01 08:43:59 GMT+0100 <info> main.js:129 - +---------------------------------+
>Wed Nov 01 08:43:59 GMT+0100 <info> main.js:130 - | Racing+ client v0.12.9 started! |
>Wed Nov 01 08:43:59 GMT+0100 <info> main.js:131 - +---------------------------------+
>Wed Nov 01 08:44:16 GMT+0100 <info> main.js:465 - Main process recieved message: steam
>Wed Nov 01 08:44:16 GMT+0100 <info> main.js:499 - Started the Greenworks child process.
>Setting breakpad minidump AppID = 250900
>Steam_SetMinidumpSteamID:  Caching Steam ID:  ### [API loaded no]`

What is the app trying to do in this phase?
Also, setting a timeout would be nice, because now it's just sitting on that screen indefinitely, it seems.

Infos:
> Racing+ client v0.12.9

> Steam client application 
> Steam API: v107 
> Steam package versions: 1496344747

`$ uname -a `
`$ Linux arch-desktop 4.13.9-1-ARCH #1 SMP PREEMPT Sun Oct 22 09:07:32 CEST 2017 x86_64 GNU/Linux `

**Comment by Zamiell** [comment]
I haven't tested the client on Linux for a while, but it should work.

>What is the app trying to do in this phase?

It's trying to get your steam ID so that it can use that to login. Here are the relevant lines:

https://github.com/Zamiell/isaac-racing-client/blob/master/src/steam.js#L74-L129

(line 115 looks like a debug line that I forgot to cleanup, so ignore that)

This steam.js is a child process. It talks to the other steam.js (in the renderer process, through the main process) here:
https://github.com/Zamiell/isaac-racing-client/blob/master/src/js/steam.js

First off, try inserting print statements all through both steam.js files to see exactly what line it is getting stuck on.

**Comment by Zamiell** [comment]
To clarify: You actually can't put print statements in a child process. You have to do:
```
process.send('getting here lol');
```
as alluded to from line 115. In the renderer process, you do:
```
globals.log.info('getting here poop');
```

**Comment by ghost** [comment]
Thanks for the tips, I got it to work. On Arch Linux (maybe on other distributions too) there are different ways to run the Steam client. One is with Steam's own installed libraries and another is to use the system's libraries. I'm usually using the latter, native method, because it's more stable and a lot of the times there are various issues with the libs provided by Steam. 

So, running Steam using the runtime method (with it's own libraries) solves the issue, and the racing client can connect successfully almost instantly.

I'd guess greenworks tries to call something that doesn't exist or just doesn't respond the way it's expected? Since it's probably not related to the Isaac racing client, I close the issue.

**Comment by Zamiell** [comment]
Nice, good to hear.
