### ISSUE TITLE
Wrong node version

### ISSUE THREAD

**Issue by guillaumepn** [Zamiell/isaac-racing-client#23]
I've tried installing the client both from the website download link and from github's repo, but in both cases I'm having a node version issue :

```
isaac-racing-client/src/lib/greenworks-osx64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
```

It seems it doesn't work with Node latest LTS version
Is it possible to update the requirement in the client to make it work ?

(I'm using Node LTS 10.15.1)

**Comment by guillaumepn** [comment]
The latest Greenworks lib version is working fine : https://github.com/greenheartgames/greenworks/releases/tag/v0.14.0

I just replaced src/lib/greenworks-osx64.node with the one in greenworks-v0.14.0-electron-v3.0.9-osx-x64.zip

**Comment by Zamiell** [comment]
Oh yeah I forgot to update the mac version when I upgraded Greenworks. Can you submit a PR?

**Comment by guillaumepn** [comment]
Done :)

**Comment by Zamiell** [comment]
nice thanks! i'll release a new version when i get home from work, if i remember
