### ISSUE TITLE
Unauthorized for all tests

### ISSUE THREAD

**Issue by z0rzi** [Zamiell/isaac-racing-client#25]
All the tests buttons take me to an error - Unauthorized page, and the Steam button launches a never ending loading..

Running on Arch Linux.

The menu:
![image](https://user-images.githubusercontent.com/22566633/53198256-3e141b00-361c-11e9-879a-b62b602e93b0.png)

The Steam loading:
![image](https://user-images.githubusercontent.com/22566633/53198282-4ff5be00-361c-11e9-8e7b-fbb6d1c681c7.png)

The tests button:
![image](https://user-images.githubusercontent.com/22566633/53198230-29d01e00-361c-11e9-87f8-5d118e3f9c83.png)

**Comment by Zamiell** [comment]
Hello,

1) The test buttons are not supposed to work - they are restricted to only work with a whitelist of IP addresses (for authorized testers). This is to prevent anonymous abuse.
2) The Steam button should work, assuming that you have Steam already opened and logged in (and you have already purchased The Binding of Isaac: Rebirth legitimately).

Did you already try looking in the logs for helpful error messages?

**Comment by z0rzi** [comment]
Thanks for your fast reply!

I do have steam opened, I'm logged it, and I purchased the game!

I just looked at the log, nothing really interesting i think, but i just noticed this error popping on my console when i click on Steam:

```
Thu Feb 21 21:34:13 GMT+0100 <info> main.js:343 - Started the "/home/zorzi/tmp/isaac-racing-client/src/steam" child process:
/home/zorzi/tmp/isaac-racing-client/node_modules/electron-is-dev/index.js:4
const app = electron.app || electron.remote.app;
                                            ^

TypeError: Cannot read property 'app' of undefined
    at Object.<anonymous> (/home/zorzi/tmp/isaac-racing-client/node_modules/electron-is-dev/index.js:4:45)
    at Object.<anonymous> (/home/zorzi/tmp/isaac-racing-client/node_modules/electron-is-dev/index.js:11:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/zorzi/tmp/isaac-racing-client/src/steam.js:7:15)
Thu Feb 21 21:34:19 GMT+0100 <info> main.js:522 - Main process recieved message: close
Thu Feb 21 21:34:19 GMT+0100 <info> main.js:498 - Wrote default values to "save1.dat".
Thu Feb 21 21:34:19 GMT+0100 <info> main.js:498 - Wrote default values to "save2.dat".
Thu Feb 21 21:34:19 GMT+0100 <info> main.js:498 - Wrote default values to "save3.dat".
```

This is probably the problem

**Comment by Zamiell** [comment]
um looks like something might be broken in the "electron-is-dev" dependency WRT linux?

have you tried running this on windows?

**Comment by z0rzi** [comment]
I haven't tried to run it on windows, and i can't really do it, I don't have any windows machines right now..

I had a problem concerning the greenworks module, so i replaced it with the latest version, could it be related?

( WRT? )

**Comment by Zamiell** [comment]
https://www.urbandictionary.com/define.php?term=wrt

it doesn't look related, the error is that it can't find electron.
you can see the code here:

https://github.com/sindresorhus/electron-is-dev/blob/master/index.js#L4

is electron installed properly? i dunno

**Comment by Zamiell** [comment]
you can always try running windows inside virtualbox

**Comment by z0rzi** [comment]
Oh my bad

Ok so I solved the problem, I directly modified the incriminated file (```/home/zorzi/tmp/isaac-racing-client/node_modules/electron-is-dev/index.js```):

I replaced
```
const app = electron.app || electron.remote.app;
```
with
```
const app = electron.app;
```

and 
```
module.exports = isEnvSet ? getFromEnv : !app.isPackaged;
```
with
```
module.exports = true;
```

That's a dirty fix but it works!

**Comment by Zamiell** [comment]
interesting, i wonder why the exports was failing

basically, the "steam.js" is a child process of the main `isaac-racing-client`.
it forks it off in order to check for steam related stuff, which seemed like it would be best done in a child process.
the child process is supposed to inherit electron and all of the other stuff.
but it looks like it isn't.

**Comment by z0rzi** [comment]
Hum.. That's surprising indeed..
________________________________

**Comment by Zamiell** [comment]
I reformatted my computer today and started with a fresh Windows 10 and the newest NodeJS. I ended up getting the same error, so it looks like it is a bug with the newest version of node + the electron-is-dev module. In the latest patch, I rewrote all the instances of electron-is-dev to use something else. Give the latest version a try and reopen if you see any other errors.
