### ISSUE TITLE
Can't connect to the server.

### ISSUE THREAD

**Issue by NarathSpring** [Zamiell/isaac-racing-client#26]
I have a problem when I try to open the client. It said: A network error occured. The server might be down! I am in China. I've tried the vpn on and off. The results are the same.
![racing](https://user-images.githubusercontent.com/27815599/54010594-5488ad80-41aa-11e9-82b5-f7e996fdb187.PNG)

**Comment by Zamiell** [comment]
Oh, it's because of some old Singapore proxy code. I'll fix it so that you can connect. However, you will have to use a VPN.

**Comment by NarathSpring** [comment]
> Oh, it's because of some old Singapore proxy code. I'll fix it so that you can connect. However, you will have to use a VPN.

Thank you very much.

**Comment by Zamiell** [comment]
Download v0.29.11 and try again. You might have to use a VPN, because I think the great firewall blocks servers hosted at: http://vpsdime.com/

**Comment by NarathSpring** [comment]
> Download v0.29.11 and try again. You might have to use a VPN, because I think the great firewall blocks servers hosted at: http://vpsdime.com/

v0.29.11 is working. Thank you so much.
